#ifndef __UNEIEXT_H
#define __UNEIEXT_H

////////////////////////////////////////////////////////////
// UNEXIM EXTENSION HEADER
// File uneiext.h
// Copyright © 1996 Asset Information Management
// Programmer: Dmitry Protopopov
////////////////////////////////////////////////////////////

#define CHAR "[^\r\n\0]"

extern const char UEOT[];
extern const char DDMMYYYY[];
extern const char CHAR3[];
extern const char VARCHAR16[];
extern const char VARCHAR25[];
extern const char VARCHAR34[];
extern const char VARCHAR35[];

extern const char VARCHARLINE35[];

/////////////////////////////////////////////////

#endif //__UNEIEXT_H