#ifndef __UNEIMF_H
#define __UNEIMF_H

//////////////////////////////////////////////////////////
// UNEXIM MESSAGE FORMAT HEADER
// File uneimf.h
// Copyright © 1996, Asset Information Management
// Copyright © 1997, Asset Information Management
// Programmer: Dmitry Protopopov
///////////////////////////////////////////////////////////

DECLARE_PARALLEL(UMT041)
DECLARE_PARALLEL(UMT044)
DECLARE_SEQUENCE(UTRAILER)

DECLARE_SEQUENCE(IFILEMICEXMESSAGE)
DECLARE_SEQUENCE(IMICEXAPPHEADER)
DECLARE_SEQUENCE(IMICEXMESSAGE)
DECLARE_SEQUENCE(OFILEMICEXMESSAGE)
DECLARE_SEQUENCE(OMICEXAPPHEADER)
DECLARE_SEQUENCE(OMICEXMESSAGE)


///////////////////////////////////////////////////////

#endif //__UNEIMF_H